version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    restart: unless-stopped
    ports:
      - "8084:80"
#     - "443:443"
    volumes:
      - web_data:/var/www/html
      - ./src:/var/www/html
      - ./default.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      catster_network:
        ipv4_address: 192.168.9.2

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    networks:
      catster_network:
        ipv4_address: 192.168.9.3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: phpmyadmin-catster
    environment:
      PMA_HOST: mariadb-catster
    depends_on:
      - mariadb
    ports:
      - "8085:80"
    networks:
      catster_network:
        ipv4_address: 192.168.9.4

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    container_name: mariadb-catster
    environment:
      MYSQL_ROOT_PASSWORD: admincatster
      MYSQL_DATABASE: dbcatster
      MYSQL_USER: root
      MYSQL_PASSWORD: catster
    networks:
      catster_network:
        ipv4_address: 192.168.9.5
    ports:
      - "3342:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql_backup:/backup
    command: --default-authentication-plugin=mysql_native_password

      
networks:
  catster_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.9.0/24

volumes:
  web_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/www/html'
  mysql_backup:
    driver: local